version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: nestvue
      MYSQL_USER: root
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - .mysql_data:/var/lib/mysql
      